DROP DATABASE IF EXISTS ProductBoi;
CREATE DATABASE IF NOT EXISTS ProductBoi;
USE productboi;

CREATE TABLE Catagories (
	CatagoryID INTEGER NOT NULL AUTO_INCREMENT,
	CatagoryName VARCHAR(15) NOT NULL,
	PRIMARY KEY (CatagoryID)
);

CREATE TABLE Product (
	ProductID INTEGER NOT NULL AUTO_INCREMENT,
	ProductName VARCHAR(15) NOT NULL,
	CatagoryID INTEGER,
	PRIMARY KEY (ProductID),
	FOREIGN KEY (CatagoryID) REFERENCES Catagories(CatagoryID)
);
